name: build workflow

on:
  push:
    paths-ignore:
    - 'README.md'
  pull_request:
    paths-ignore:
    - 'README.md'    
  workflow_dispatch:

env:
  SOLUTION_DIRECTORY : src
  SOLUTION_PATH : src/ConsoLovers.ConsoleToolkit.Core.sln
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: checkout branch
      uses: actions/checkout@v3
    
#    - name: restore certificate
#      run: |
#        New-Item -ItemType directory -Path certificate
#        Set-Content -Path certificate\FluentSetups.txt -Value '${{ secrets.FLUENT_SETUP_CERTIFICATE }}'
#        certutil -decode certificate\FluentSetups.txt certificate\FluentSetups.snk
#        dir certificate

    - name: setup NuGet.exe
      uses: NuGet/setup-nuget@v1.0.6
      with:
        nuget-version: latest
        nuget-api-key: ${{secrets.NUGET_API_KEY}}
    
    - name: restore NuGet packages
      run: nuget restore ${{ env.SOLUTION_PATH }}
    
    - name: setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: build solution
      run: msbuild ${{ env.SOLUTION_PATH }} -property:Configuration=Release

    - name: show build results
      run: dir ${{ env.SOLUTION_DIRECTORY }}\Release
    
    - name: show binaries
      run: dir testBinaries
 
    - name: setup VSTest.console.exe
      uses: darenm/Setup-VSTest@v1

    - name: run unit tests
      run: vstest.console.exe {{ env.SOLUTION_DIRECTORY }}\Release\net6.0\ConsoLovers.ConsoleToolkit.Core.UnitTests.dll

  publish:
    needs: [build]
    runs-on: windows-latest
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
    - name: download artifacts
      uses: actions/download-artifact@v3.0.0
      with:
        name: nugetPackage
        path: packages
        
    - name: show packages
      run: dir packages
      
    - name: setup NuGet.exe
      uses: NuGet/setup-nuget@v1.0.6
      with:
        nuget-version: latest
      
    - name: push to nuget.org
      run: nuget push packages\*.nupkg -src https://api.nuget.org/v3/index.json -ApiKey ${{secrets.NUGET_API_KEY}} -SkipDuplicate
  
